# Generated by Django 2.2.2 on 2019-06-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190618_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='content_pics'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
